### PR TITLE
Feature/9 identify a barrier page

### LINKED ISSUE #9: Dev - Identify a new barrier (worksheet) page
Build ["Identify a barrier"](https://www.figma.com/proto/SqRfWwcyuclFvGCq47zJf6/Passport---V5.0.0?node-id=2%3A8&scaling=min-zoom&page-id=0%3A1) page.

### PR DESCRIPTION
**Pull request by yonikid15**
Resolves #9 and #44

### CODE REVIEW

**Comment by brindasasi** [comment]
.

**Review by brindasasi — CHANGES_REQUESTED** [review]
filter looks great Yoni! 
Couple things 
* title needs to say `Identify a new barrier`
* I think you are working on this already , can't tab to Work Situation . Also `You are currently viewing barriers related to` section only 1 radio button is enabled. Was that a requirement?  I thought all should be enabled. 
* `Can't find a barrier that meets your needs? Define your own` this should be active link and I think it should link to the page you have developed already.

**Comment by yonikid15** [comment]
Okay I think I got everything you mentioned.

**Review by brindasasi — APPROVED** [review]

**Comment by brindasasi** [comment]
LGTM

**Pull request merged**
