### PR TITLE
View/Action Solution page

### LINKED ISSUE #46: [Passport user] - View/action a solution page

### PR DESCRIPTION
**Pull request by yonikid15**
REVIEW THIS BEFORE #70 

Resolves #46

### CODE REVIEW

**Comment by brindasasi** [comment]
- Screen Shot 2022-05-04 at 10 51 17 AM
Original Definition label needs to be removed 
- Please remove addition information component as we removed it  from earlier UIs.
- there is a discrepancy in this below section from the requirement . There should be 2 check boxes and the content should be 

- My manager and I have had a conversation about the barrier and solution(s) [DATE STAMP] (required)
- My manager and I have agreed to implement the identified solution(s) [DATE STAMP] (required)

Screen Shot 2022-05-04 at 10 57 37 AM
Screen Shot 2022-05-04 at 10 57 44 AM

- there should be 1 more check box for Manager Signature
Screen Shot 2022-05-04 at 11 08 56 AM

- I love the attachment icon in yours ..but the wireframe use different icon. If we are going with this , lets  use the same for mine
-  change Exmple Solution 2 to **Noise Cancelling Headphone** 
Screen Shot 2022-05-04 at 11 16 19 AM

**Review by brindasasi — CHANGES_REQUESTED** [review]
Great work Yoni! Please look at  some content corrections as above

**Comment by RM-1978** [comment]
May 4: Note that OPSA will review all the UIs in the Passport User flow at once  on May 6 to approve or approve with minor changes. @JoshBeveridge @brindasasi @gobyrne @yonikid15

**Comment by yonikid15** [comment]
The `My manager and I have agreed to implement the identified solution(s) [DATE STAMP] (required)` and the `manager signature checkbox`  is now not needed since it's handled on the manger side. These changes came from our standup meeting from the other day.

**Review by brindasasi — APPROVED** [review]
LGTM

**Pull request merged**
