### PR TITLE
Identify a solution page

### PR DESCRIPTION
**Pull request by yonikid15**

### CODE REVIEW

**Review by brindasasi — CHANGES_REQUESTED** [review]
looks great some minor improvements as described below

- Screen Shot 2022-04-21 at 2 41 51 PM

These needs to be removed from the left side as per  the document

- `Please select the link below to customize the solution you have selected`
this line should be right above the button in the footer and below the ruler

**Comment by yonikid15** [comment]
> * `Please select the link below to customize the solution you have selected`
>   this line should be right above the button in the footer and below the ruler

It doesn't specify that it should be "below the ruler". I can ask Rosalie.

**Comment by yonikid15** [comment]
@brindasasi So Rosalie said that it looks okay 👍

**Review by brindasasi — APPROVED** [review]

**Comment by brindasasi** [comment]
LGTM

**Pull request merged**
